export const FETCH_SENSORS = "FETCH_SENSORS";
export const FETCH_SEGMENTS = "FETCH_SEGMENTS";
export const FETCH_SEGMENTS_EVENTS = "FETCH_SEGMENTS_EVENTS";
export const FETCH_SEGMENTS_LEAKS_BEGIN = "FETCH_SEGMENTS_LEAKS_BEGIN";
export const FETCH_SEGMENTS_LEAKS_SUCCESS = "FETCH_SEGMENTS_LEAKS_SUCCESS";
export const FETCH_SEGMENTS_LEAKS_FAILURE = "FETCH_SEGMENTS_LEAKS_FAILURE";
export const FETCH_SEGMENTS_LEAK = "FETCH_SEGMENTS_LEAK";
export const FETCH_COSTS = "FETCH_COSTS";
export const FETCH_LEAK_LITRES_BEGIN = "FETCH_LEAK_LITRES_BEGIN";
export const FETCH_LEAK_LITRES_SUCCESS = "FETCH_SEGMENTS_LEAKS_SUCCESS";
export const FETCH_LEAK_LITRES_FAILURE = "FETCH_LEAK_LITRES_FAILURE";
export const FETCH_WASTAGE_DAILY = "FETCH_WASTAGE_DAILY";
export const FETCH_WASTAGE_MONTHLY = "FETCH_WASTAGE_MONTHLY";
export const FETCH_WASTAGE_SEASONALLY = "FETCH_WASTAGE_SEASONALLY";
export const FETCH_WASTAGE_DAILY_BEGIN = "FETCH_WASTAGE_DAILY_BEGIN";
export const FETCH_WASTAGE_DAILY_SUCCESS = "FETCH_WASTAGE_DAILY_SUCCESS";
export const FETCH_WASTAGE_DAILY_FAILURE = "FETCH_WASTAGE_DAILY_FAILURE";
export const FETCH_WASTAGE_MONTHLY_BEGIN = "FETCH_WASTAGE_MONTHLY_BEGIN";
export const FETCH_WASTAGE_MONTHLY_SUCCESS = "FETCH_WASTAGE_MONTHLY_SUCCESS";
export const FETCH_WASTAGE_MONTHLY_FAILURE = "FETCH_WASTAGE_MONTHLY_FAILURE";
export const FETCH_WASTAGE_SEASONALLY_BEGIN = "FETCH_WASTAGE_SEASONALLY_BEGIN";
export const FETCH_WASTAGE_SEASONALLY_SUCCESS = "FETCH_WASTAGE_SEASONALLY_SUCCESS";
export const FETCH_WASTAGE_SEASONALLY_FAILURE = "FETCH_WASTAGE_SEASONALLY_FAILURE";


export const handleErrors = response => {
  if (!response.ok) {
    throw Error(response.statusText);
  }
  return response;
};
