 export const FETCH_SENSORS ='FETCH_SENSORS';
 export const FETCH_SEGMENTS ='FETCH_SEGMENTS';
 export const FETCH_SEGMENTS_EVENTS = 'FETCH_SEGMENTS_EVENTS';
 export const FETCH_SEGMENTS_LEAKS = 'FETCH_SEGMENTS_LEAKS';
 export const FETCH_LEAKS_COSTS = 'FETCH_LEAKS_COSTS';