import React from "react";
import ReactDOM from "react-dom";
import "./index.scss";
import App from "./App";
import * as serviceWorker from "./ServiceWorker";
import SensorTableComponent from "./Components/SensorsTable";
import HistoryTable from "./Components/HistoryTable";
import AlertTable from "./Components/AlertTable";
ReactDOM.render(<App />, document.getElementById("root"));
serviceWorker.register(); 
